version: "3.9"
services:
  pb-back:
    container_name: pb-back
    build:
      context: ../pb-back/.
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../pb-back:/app
    depends_on:
      - pb-redis
      - pb-postgres
    networks:
      - pb-net
    env_file:
      - ../pb-back/Dockerenv.dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@pb-postgres:5432/pb_development?pool=6
      - TEST_DATABASE_URL=postgres://postgres:postgres@pb-postgres:5432/pb_test?pool=6
      - REDIS_URL=redis://pb-redis:6379
      - REDIS_DB=0
    command:
      [
        "/bin/sh",
        "-c",
        "rm -f /app/tmp/pids/server.pid && rails s -b 0.0.0.0 -p 3000"
      ]
    
  pb-redis:
    image: redis:alpine
    container_name: pb-redis
    volumes:
      - pb-redis-data:/data
    networks:
      - pb-net

  pb-postgres:
    image: postgres:12
    container_name: pb-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pb_development
    volumes:
      - pb-postgres-data:/var/lib/postgresql/data
    networks:
      - pb-net

volumes:
  pb-redis-data:
  pb-postgres-data:


networks:
  pb-net:
