development:
  adapter: <%= ENV['DB_ADAPTER'] ||= 'postgresql' %>
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] ||= '5432' %>
  database: <%= ENV['DB_NAME'] %>
  
test:
  adapter: postgresql
  database: <%= ENV['DB_NAME_TEST'] %>
  pool: 5
  timeout: 5000
  user: <%= ENV['DATABASE_USERNAME'] %>

production:
  adapter: postgresql
  database: <%= ENV['PRODUCTION_DATABASE'] %>
  pool: 5
  timeout: 5000
  user: <%= ENV['DATABASE_USERNAME'] %>